# 내장 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
# View Resolver 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp
  # 데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
