# 내장 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

# View Resolver 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp
  # 데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  # JPA 설정
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # Devtools 설정
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

# 카카오 비밀번호
kakao:
  default:
    password: kakao123